name: Build 1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '22'


      - name: install dependencies
        run: |
          npm install

      - name: lint
        run: |
          echo npm run lint

  test:
    runs-on: ubuntu-22.04
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '22'


      - name: install dependencies
        run: |
          npm install

      - name: test
        run: |
          echo npm run test


  deploy:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '22'


      - name: install dependencies
        run: |
          npm install

      - name: build
        run: |
          echo npm run build

      - name: deploy
        run: |
          echo simulating deploying

